#before_script:
#- apt-get update -qq && apt-get install -y -qq golang
#- go get github.com/constabulary/gb/...
# ref: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/.gitlab-ci.yml#L1

image: golang:1.6

stages:
  - build

build_with_gb:
  stage: build
  script:
    - (if [[ "$(go version)" == *"go version go1.6"* ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
    - cd /builds/apihussain1/oauthtest
    - go get github.com/constabulary/gb/...
    - gb vendor fetch github.com/fatih/color
    - gb build
