#before_script:
#- apt-get update -qq && apt-get install -y -qq golang
#- go get github.com/constabulary/gb/...
#
# From go build example: https://gitlab.com/gitlab-org/gitlab-ce/blob/76109d754e167e05db7897f6b89a36b2fadffc65/doc/ci/examples/test-golang-application.md

image: golang:1.6

stages:
  - install-environment
  - build

before_script:
  - apt-get update -y -qq

install-go:
  stage: install-environment
  script:
    - export CURRENT_BUILD_PATH=${pwd}
    - ls -la $CURRENT_BUILD_PATH
    - mkdir -p $HOME/golang && mkdir -p $HOME/gopath
    - curl https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz 2>/dev/null > go1.6.2.linux-amd64.tar.gz
    - tar -C $HOME/golang -xzf go1.6.2.linux-amd64.tar.gz
    - export GOROOT=$HOME/golang/go
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    - ls -la $HOME
    - go version
    - (if [[ "$(go version)" == *"go version go1.6"* ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);

build_with_gb:
  stage: build
  script:
    - ls -la $CURRENT_BUILD_PATH
    - ls -la $HOME
    - (if [[ "$(go version)" == *"go version go1.6"* ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
    - cd ${CURRENT_BUILD_PATH}
    - go get github.com/constabulary/gb/...
    - gb build
