stages:
  - install-environment
  - build

install-go:
  stage: install-environment
  script:

before_script:
- apt-get update -qq && apt-get install -y -qq golang
- go get github.com/constabulary/gb/...

build_with_gb:
  stage: build
  script:
    - gb build