#before_script:
#- apt-get update -qq && apt-get install -y -qq golang
#- go get github.com/constabulary/gb/...
#
# From go build example: https://gitlab.com/gitlab-org/gitlab-ce/blob/76109d754e167e05db7897f6b89a36b2fadffc65/doc/ci/examples/test-golang-application.md

stages:
  - install-environment
  - build

install-go:
  stage: install-environment
  script:
    - ls /builds/apihussain1/oauthtest
    - export CURRENT_BUILD_PATH=${pwd}
    - echo $PATH
    - mkdir -p $HOME/golang
    - mkdir -p $HOME/gopath
    - curl https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz 2>/dev/null > go1.6.2.linux-amd64.tar.gz
    - tar -C $HOME/golang -xzf go1.6.2.linux-amd64.tar.gz
    - export GOROOT=$HOME/golang/go
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:%GOROOT/bin
    - export PATH=$PATH:$GOPATH/bin
    - echo $PATH
    - (if [[ "$(go version)" == *"go version go1.6"* ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
    - go version
    - go env
    - which go

build_with_gb:
  stage: build
  script:
    - cd /builds/apihussain1/oauthtest
    - go get github.com/constabulary/gb/...
    - gb build
